/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/screens/auth/CreateAccount`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(auth)'}/details` | `/details`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/components/icons/EyeOff`; params?: Router.UnknownInputParams; } | { pathname: `/components/icons/EyesIcon`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/auth/CreateAccount`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(auth)'}/details` | `/details`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(auth)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/components/icons/EyeOff`; params?: Router.UnknownOutputParams; } | { pathname: `/components/icons/EyesIcon`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/screens/auth/CreateAccount${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${'/(auth)'}/details${`?${string}` | `#${string}` | ''}` | `/details${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${'/(auth)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/components/icons/EyeOff${`?${string}` | `#${string}` | ''}` | `/components/icons/EyesIcon${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/screens/auth/CreateAccount`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(auth)'}/details` | `/details`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/components/icons/EyeOff`; params?: Router.UnknownInputParams; } | { pathname: `/components/icons/EyesIcon`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
